### PR TITLE
Added basic footer with links to ACM Website, CS@Mines Website, Discord, and Github. 

### PR DESCRIPTION
**Pull request by umbertogherardi**

### CODE REVIEW

**Review by umbertogherardi — COMMENTED** [review]
Apologies on the incorrect message; I have added a basic *footer, not navbar. Closes #3

**Comment by ezrichards** [comment]
@umbertogherardi, make sure to `git pull` (ideally before) making any changes. Your branch was behind main so I just updated it with the changes from main, but it caused a merge conflict with Keenan's navbar updates.

Not a big deal, but just something to keep in mind in the future. I often forget to pull too, it happens! :)

**Review by ezrichards — CHANGES_REQUESTED** [review]
Hey Umberto, great work, the footer looks fantastic!

Due your local repository being a little behind the remote `main`, you didn't see the `static` folder. I would like to make a couple of changes accordingly before accepting these changes.
- Move the content of `styles.css` to `static/index.css` (this is where I was going to put our styling)
- Delete the old `styles.css` file and adjust `index.html` accordingly (we'll have an extra stylesheet in the head. We only need one.)
- Go ahead and throw the `site_images` folder into the `static` folder too please.

Great job though! I'm a big fan of using Google Fonts (and was going to create an issue for that) but I'm pleased that you took the time to pick out a font for the site.

**Comment by umbertogherardi** [comment]
> @umbertogherardi, make sure to `git pull` (ideally before) making any changes. Your branch was behind main so I just updated it with the changes from main, but it caused a merge conflict with Keenan's navbar updates.
> 
> Not a big deal, but just something to keep in mind in the future. I often forget to pull too, it happens! :)

**Comment by umbertogherardi** [comment]
Hey Ethan! Thanks so much for the feedback! I'll get right on this stuff ASAP and be sure to check for pulls in the future. Also, I think I might've accidentally closed this issue while trying to respond to you; my apologies, I'm still trying to learn the in-and-outs of GitHub :)

**Review by ezrichards — APPROVED** [review]
Looks good to me, thanks Umberto!

Note that I made a small fix wherever you referenced the static folder: you referenced it as `/static/index.css` for instance, but that will actually start looking for files on your computer. You need to add a period (so like `./static/index.css`) for it to start looking within the project.

**Comment by ezrichards** [comment]
@umbertogherardi ensure that you `git pull` and `git switch main` locally (this branch will be deleted).

**Pull request merged**
